# Generated by Django 5.1.2 on 2024-10-31 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancy.job'),
        ),
    ]
