# Generated by Django 5.1.2 on 2024-10-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_applicant_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='job_id',
            new_name='job',
        ),
    ]
